longhorn/longhorn-share-manager

- package/Dockerfile
- scripts/package
https://github.com/longhorn/longhorn/issues/2091
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
> package: update base image to get the latest changes

- package/Dockerfile
https://github.com/longhorn/longhorn/issues/2111
Signed-off-by: Joshua Moody <joshua.moody@rancher.com>
> Switch to building ganesha on an ubuntu image

- .gitignore
- package/Dockerfile
Signed-off-by: David Ko <dko@suse.com>
ref: https://github.com/longhorn/longhorn/issues/2763
> Frequently update packages when building image

- Dockerfile.dapper
- package/Dockerfile
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi.suse.com>
> update Dockerfile & Dockerfile.dapper

- Dockerfile.dapper
- package/Dockerfile
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> update v1_20210416 base image

- .drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> update drone config

- .drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> [backport] [v1_20210416] update drone config

- Dockerfile.dapper
- package/Dockerfile
Ref: https://github.com/longhorn/longhorn/issues/2939
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> change base image to SUSE BCI

- .drone.yml
- Dockerfile.dapper
- scripts/package
This PR adds support to build on s390x architecture.
> Add s390x support

- Dockerfile.dapper
[Longhorn 4032](https://github.com/longhorn/longhorn/issues/4032)
> Update protobuf to 3.18.0

- package/Dockerfile
[Longhorn 4035](https://github.com/longhorn/longhorn/issues/4035)
> Add awk into image

- package/Dockerfile
- pkg/server/nfs/nfs_server.go
[Longhorn 4351](https://github.com/longhorn/longhorn/issues/4351)
> Update nfs-ganesha to v4

- pkg/server/nfs/nfs_server.go
Signed-off-by: Ray Chang <ray.chang@suse.com>
[Longhorn #2380](https://github.com/longhorn/longhorn/issues/2380)
1. Add LOG block in defaultConfig
2. Remove defaultLogFile path as parameter
> Add LOG block in configuration to redirect nfs-ganesha log to stdout.

- package/Dockerfile
- pkg/server/nfs/nfs_server.go
https://github.com/longhorn/longhorn/issues/2293
Depends on https://github.com/longhorn/nfs-ganesha/pull/2
> Recovery-backend: replace `fs_ng` with `longhorn`

- package/Dockerfile
- pkg/crypto/crypto.go
- pkg/server/nfs/export.go
- pkg/server/nfs/nfs_server.go
- pkg/server/share_manager.go
https://github.com/longhorn/longhorn/issues/5083
> Update nfs ganesha 4.2.1

- package/Dockerfile
- pkg/crypto/crypto.go
- pkg/server/nfs/export.go
- pkg/server/nfs/nfs_server.go
- pkg/server/share_manager.go
Longhorn 5083
(cherry picked from commit 177cf45)
> Update nfs-ganesha to v4.2.1

- package/Dockerfile
> Dockerfile: update nfs-ganesha to v4.2.3

- package/Dockerfile
> nfs-ganesha: update to v4_20230310

- package/Dockerfile
- scripts/package
build: use bci image
For https://github.com/longhorn/longhorn-share-manager/pull/61#issuecomment-1476040838
Signed-off-by: Yang Chiu <yang.chiu@suse.com>
> build: use bci image

- package/Dockerfile
ref: https://github.com/longhorn/longhorn/issues/5590
> chore: update nfs ganesha version

- pkg/server/share_manager.go
ref: [longhorn/longhorn#5961](https://github.com/longhorn/longhorn/issues/5961)
remount the mountpoint in share-manager if the mountpoint become read-only
> fix(share-manager): remount volume if mount point became ro

- integration/rpc/share_manager/smrpc_pb2.py
- integration/rpc/share_manager/smrpc_pb2_grpc.py
- pkg/client/share_manager_client.go
- pkg/rpc/server.go
- pkg/rpc/smrpc.pb.go
- pkg/rpc/smrpc.proto
- pkg/server/nfs/export.go
- pkg/server/nfs/nfs_server.go
- pkg/server/share_manager.go
- pkg/util/mount.go
- pkg/util/util.go
- pkg/volume/volume.go
> grpc: implement Mount method

- scripts/build
Longhorn/longhorn#7135
e2e
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5345/
> Disable CGO support

- package/Dockerfile
https://github.com/longhorn/longhorn/issues/6000
Needs my working branch [longhorn-ganesha-v5-V5.7](https://github.com/james-munson/nfs-ganesha/tree/longhorn-ganesha-v5-V5.7) pushed to longhorn/nfs-ganesha/longhorn-ganesha-v5 first.  (Don't have a PR for that, since the target branch doesn't exist.)
~Then this should be revised to use that tag for the build.~  Done.  See [below](https://github.com/longhorn/longhorn-share-manager/pull/113#issuecomment-1877704257)
> Use nfs-ganesha v5 branch.

- package/Dockerfile
> Dockerfile: update nfs-ganesha to v5_20240408

- package/Dockerfile
> Dockerfile: update nfs-ganesha to v4_20240412

- package/Dockerfile
> Dockerfile: update nfs-ganesha to v5_20240412

- scripts/validate
https://github.com/longhorn/longhorn/issues/7448
> fix: add timeout and remove new-from-rev

- package/Dockerfile
Longhorn 8394
Issue longhorn/longhorn#8394
> Dockerfile: update nfs-ganesha to v5_20240430

- pkg/client/share_manager_client.go
> Remove deprecated grpc.Dial use, replace with grpc.NewClient

- package/Dockerfile
> chore(dockerile): update nfs-ganesha repo to rancher/nfs-ganesha

- package/Dockerfile
Issue longhorn/longhorn#8722, longhorn/longhorn#8721
Refresh and update release image system packages.
- TODO: backport to master and v1.7.x.
`None`
> build(image): always update system package

- package/Dockerfile
Issue longhorn/longhorn#10096
Build with missing dependency.
`None`
`None`
> fix(build): failed to load libjson-c.so.5

- package/Dockerfile
Issue:  https://github.com/longhorn/longhorn/issues/8523
Update v1.7.x to nfs-ganesha v6.3 to address some memory issues.
> chore: update to nfs-ganesha v6.5

- package/Dockerfile
Issue Longhorn/longhorn#10979
Hotfix for Longhorn 10621
> fix: update nfs-ganesha to v6_20250525
